# Create a workflow for React projects that builds, tests on push and pull request events

name: React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies using clean install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
